server:
#  ssl:
#    enabled-protocols: TLSv1.3
#    key-alias: mykey
#    key-store: test.p12
#    key-store-password: 123456
#    key-password: 123456
#    trust-store: testTrust.p12
#    trust-store-password: 123456
#  port: 8443

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create-drop
  h2:
    console:
      enabled: true